function love.conf(t)
  t.identity="nokiajam4"
  t.appendidentity=false
  t.version="11.3"
  t.console=false
  
  t.window.title="UPbeat"
  t.window.width=84 
  t.window.height=48
  t.window.borderless=false
  t.window.resizable=true
  t.window.minwidth=84 
  t.window.minheight=48
  t.window.fullscreen=false
  t.window.fullscreentype="desktop"
  t.window.vsync=1
  t.window.msaa=0
  t.window.depth=nil
  t.window.stencil=nil
  t.window.display=1
  t.window.highdpi=false
  t.window.usedpiscale=true
  t.window.x=nil
  t.window.y=nil
  
  t.modules.audio=true
  t.modules.data=true
  t.modules.event=true
  t.modules.font=true
  t.modules.graphics=true
  t.modules.image=true
  t.modules.joystick=false
  t.modules.keyboard=true
  t.modules.math=true
  t.modules.mouse=true
  t.modules.physics=false
  t.modules.sound=true
  t.modules.system=true
  t.modules.thread=false
  t.modules.timer=true
  t.modules.touch=false
  t.modules.video=false
  t.modules.window=true
end
